# configs/datasets/soda_a_05_small_patches.yaml
name: "SODA_A_05_small_patches"
description: "SODA-A dataset small subset (patched to 640x640)"

format: "coco"

paths:
  root: "/home/vlv/Documents/master/computervision/SODA_dataset/SODA_A_05_small"
  train: "/home/vlv/Documents/master/computervision/SODA_dataset/SODA_A_05_small/train_patches"
  val: "/home/vlv/Documents/master/computervision/SODA_dataset/SODA_A_05_small/test_patches"  # Or create val_patches
  test: "/home/vlv/Documents/master/computervision/SODA_dataset/SODA_A_05_small/test_patches"

annotation_file: "_annotations.coco.json"

image_size: [640, 640]  # Now matches patch size
num_channels: 3
num_classes: 9

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

min_bbox_size: 1